services:
  - type: web
    name: portfolio-front
    env: static
    buildCommand: echo "Build jรก pronto - usando build/web existente"
    staticPublishPath: ./build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
